[auth]
enabled = true
site_url = "http://localhost:3000"  # Keep this for local development
additional_redirect_urls = ["https://staging.example.com"] 
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true  # ✅ Already correct
secure_password_change = false
max_frequency = "1m0s"  # ✅ Already correct
otp_length = 6
otp_expiry = 86400  # 
