name: Supabase Schema Migration

on:
  push:
    branches:
      - dev
      - main

jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest  # Always use latest CLI

      - name: Select Project Ref
        run: |
          if [ "${GITHUB_REF##*/}" = "dev" ]; then
            echo "PROJECT_REF=${{ secrets.PROJECT_REF_DEV }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "PROJECT_REF=${{ secrets.PROJECT_REF_PRODUCTION }}" >> $GITHUB_ENV
          fi

      - name: Select DB Password  
        run: |
          if [ "${GITHUB_REF##*/}" = "dev" ]; then
            echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD_MAIN }}" >> $GITHUB_ENV
          fi

      - name: Link Supabase Project
        run: supabase link --project-ref ${{ env.PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ env.SUPABASE_DB_PASSWORD }}

      - name: Apply migrations to remote DB
        run: supabase db push --linked --include-all
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ env.SUPABASE_DB_PASSWORD }}
